### PR TITLE
Create Regional County Geography

### PR DESCRIPTION
**Pull request by jdev42092**
All relevant data sets and shapefiles are already on L:\

### CODE REVIEW

**Comment by jdev42092** [comment]
@rpitingolo @NeighborhoodInfoDC/review Here are the programs to create the regional counties data set. They are ready for review.

**Comment by rpitingolo** [comment]
@jdev42092 thanks. I'm reviewing.

**Comment by rpitingolo** [comment]
@jdev42092 please merge and finalize.

**Comment by jdev42092** [comment]
@rpitingolo @NeighborhoodInfoDC/review The weight creation files have been updated and this is ready for review.

**Comment by rpitingolo** [comment]
@jdev42092 thanks. I'll review.

**Comment by rpitingolo** [comment]
@jdev42092 please go ahead and merge/finalize the counties. Thanks.

**Pull request merged**
