### PR TITLE
Develop Cluster 2017-General

### PR DESCRIPTION
**Pull request by npstrayer**
@rpitingolo

### CODE REVIEW

**Comment by rpitingolo** [comment]
@npstrayer this is ready for review, correct?

**Comment by npstrayer** [comment]
Yes, sorry I forgot to specify

________________________________

**Comment by rpitingolo** [comment]
@npstrayer thanks. This looks good but I discovered another issue with the format, so please standby while I fix that before moving to the other issues.

**Comment by rpitingolo** [comment]
@npstrayer OK. I've fixed the format issued and copied this macro over to L. Nothing more to do on this one. Please move on to the next issue.

**Comment by rpitingolo** [comment]
@npstrayer Please remember to update the program header (I updated this one for you).

**Pull request merged**
