### PR TITLE
update weights

### PR DESCRIPTION
**Pull request by eburton9**
@rpitingolo for all 6 files received these errors: blockYY_ward22 data does not exist
blockpopdata does not exist
wt_bgYY_ward22.data does not exist
I tried to change some things to fix it, but couldn't figure out the issues.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eburton9 I believe you are missing the library prefix in one of the parameters. So instead of `block_corr_ds = Block20_ward22` try it with `block_corr_ds = General.Block20_ward22`

**Comment by eburton9** [comment]
@rpitingolo still getting same errors as before for wt_bg00_ward22
many invalid block group errors for wt_bg20_ward22

**Comment by rpitingolo** [comment]
@eburton9 I  think block_pop_var has the wrong variable name on wt_bg00_ward22. I'll look into wt_bg20_ward22.

**Comment by rpitingolo** [comment]
@eburton9 the GeoBG2020 variable didn't create correctly on Block20_Ward22 so we'll have to do a bug fix to go back and correct that.

**Comment by rpitingolo** [comment]
@eburton9 good to go! Please go ahead and merge, sync and finalize this. Thanks!

**Pull request merged**
