### PR TITLE
Step 2: create StantonCommons.sas

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo  step 2 ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. I'll review.

**Comment by rpitingolo** [comment]
@maggiesu0725 I batched submitted stantoncommons.sas. Please keep this branch open and continue on to step 3.

**Comment by rpitingolo** [comment]
@maggiesu0725 I see your commits now and will review.

**Comment by rpitingolo** [comment]
@ptatian Understand. I'm checking on this.

**Comment by maggiesu0725** [comment]
@rpitingolo weighting files are ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 I'm getting errors on all the programs. Did you get ERROR: [Calc_weights_from_blocks] Invalid or missing value of geography (geo2=STANTONCOMMONS) when you ran them?

**Comment by rpitingolo** [comment]
@ptatian can you please  take a look at the error we're getting in the /weights/ programs? (error pasted above). We did all the previous steps so I'm stumped as to why it's not working.

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 OK. I’ll have a look. It will be later today or tomorrow.

**Comment by rpitingolo** [comment]
@ptatian @maggiesu0725 Sure. Thanks

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 The error message is being generated by the _%Calc_weights_from_blocks()_ macro, from this section of code:

```
  %if %sysfunc( putc( &geo2, $geoval. ) ) ~= %then %do;
    %let geo2suf = %sysfunc( putc( &geo2, $geosuf. ) );
    %let geo2name = %sysfunc( putc( &geo2, $geoslbl. ) );
    %let geo2dlbl = %sysfunc( putc( &geo2, $geodlbl. ) );
    %let geo2fmt = %sysfunc( putc( &geo2, $geoafmt. ) );
    %let geo2vfmt = %sysfunc( putc( &geo2, $geovfmt. ) );
  %end;
  %else %do;
    %err_mput( macro=Calc_weights_from_blocks, msg=Invalid or missing value of geography (geo2=&geo2). )
    %goto exit_macro;
  %end;
```

The key is the _%if_ statement, which is checking whether the value passed to _geo2=_ is the name of a valid geography based on the _$geoval._ format. It appears the _$geoval._ format has not yet been updated to include the STANTONCOMMONS geography. _$geoval._ is updated by **Prog\Geo_level_formats.sas**. This program needs to be batch submitted on L: to update the format. Once you do that, the weight programs should run properly. 

Let me know if you have any other questions.

**Comment by ptatian** [comment]
@maggiesu0725 @rpitingolo Just as another note, branch names on GitHub are case sensitive so, in the future, please use **only lowercase letters** when creating branch names. Thank you.

**Comment by rpitingolo** [comment]
@maggiesu0725 OK. Let me take a look.

**Comment by rpitingolo** [comment]
@ptatian Hi Peter. We are getting reapting values errors because of the highlighted cells in this file L:\Libraries\General\Doc\Geographic levels.xlsx 

I honestly can't remember why we added the metro area block, bg and tract formats. Do we use them? It seems like the data to format macro won't work if there are duplicate rows like we have now.  Thanks.

**Comment by rpitingolo** [comment]
@maggiesu0725 this looks good now. Please merge this pull request, do a final batch submission of the weights programs on L and close the issue. Thanks!

**Pull request merged**
