### PR TITLE
octo2000 blocks

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. will review.

**Comment by rpitingolo** [comment]
@maggiesu0725 I made some edits that you can see in github. Please move on to create Block10_cluster2017.sas . Thanks!

**Comment by maggiesu0725** [comment]
@rpitingolo create Block10_cluster2017.sas  ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. Will review.

**Comment by rpitingolo** [comment]
@maggiesu0725 i made a few edits. I'm not sure what happened with the reverted pull request but I can't see the commits I made early on this branch now. Once we figure that out we can finalize this on Monday. Thanks for your help.

**Comment by rpitingolo** [comment]
@maggiesu0725 ready to merge and finalize. I'll come by to help you in a few minutes.

**Pull request merged**
