### PR TITLE
updates to anc02, anc12, bpk

### PR DESCRIPTION
**Pull request by eburton9**
I haven't actually changed anything in the other files, just was creating new ones all at once

### CODE REVIEW

**Comment by eburton9** [comment]
@rpitingolo

**Comment by rpitingolo** [comment]
@eburton9 OK this is back on track. Please look at my edits to wt_bg20_anc02.sas and wt_bg20_anc02.sas. The key thing is that you need to have General. in front of the correspondence dataset and Census. in front of the Census pl dataset. Once you do that you shouldn't get any more errors in your log.

**Comment by eburton9** [comment]
@rpitingolo here are the weight updates. Both  bg_city, tr_city, bg_voterpre12, and tr_voterpre12 have errors (voterpre12: invalid voting precinct and couldn't find city data). Then tr_ward02 and bg_cl17 also had errors where the data were not found.

**Comment by rpitingolo** [comment]
@eburton9 thanks! I will check those out first.

**Comment by rpitingolo** [comment]
@eburton9 I just pushed a few edits

- bg_city and tr_city required an extra datastep to create the city variable, which I added
- tr_ward02 and bg_cl17 had some old code that was causing issues. I removed it and it's OK now
- bg_voterpre12 and tr_voterpre12 is a format issue that we will have to deal with in a separate issue. It's not a fatal error so we'll just run it without the format for now.

Please go ahead and merge, sync and batch submit each of these programs one at a time to close out this issue. Thanks!

**Pull request merged**
