### PR TITLE
updated to 2020 and took out general. path to data

### PR DESCRIPTION
**Pull request by eburton9**
@rpitingolo

### CODE REVIEW

**Comment by rpitingolo** [comment]
@eburton9 good start! A few things to note on review.

1. In the %Data_to_format macro, you will need to update  FmtName= parameter to replace the '1' with a '2'. For example $bk2wdaf - I went ahead and made the change in the Ward and Cluster programs so that you could see.
2. %File_info is an old macro that we have replaced with %Finalize_data_set. The cluster program already had it, but in the Ward program I replaced %File_info with %Finalize_data_set. So please made that adjustment if you find others that use the old macro.

Please let me know if you have other questions. Otherwise please continue with the other programs from the issue. Thanks!

**Comment by rpitingolo** [comment]
@eburton9 if it's helpful, the format name you want to use in the %Data_to_format macro should match what is in the 2020 correspondence column of this spreadsheet: 

\\sas1\dcdata\Libraries\General\Doc\Geographic levels.xlsx

**Comment by eburton9** [comment]
@rpitingolo here are the other program updates. The only errors are on the city, eor, and tract10 ones, the rest I could debug but couldn't figure out why the data wasn't working on those three. The city and eor files seem to be really short too, I don't know if they are incomplete? Thanks!

**Comment by rpitingolo** [comment]
@eburton9 a few of these are not working quite right but it's hard to notice because they don't show up as errors in the log. I am working on debugging now. 

Can you please also make and commit Block20_Anc02.sas and Block20_Anc12.sas? I forgot those on the original issue.

**Comment by eburton9** [comment]
@rpitingolo Sorry about that! Here are those two

**Comment by rpitingolo** [comment]
@eburton9 great, thanks. I think we are nearly there. I want to do one more pass through to double check everything, so if you could be ready to finalize tomorrow morning we can get this done and move on to the final step.

**Comment by rpitingolo** [comment]
@eburton9 These are now good to go. Please go ahead and merge this pull request, sync on SAS1 and then batch submit these programs one at a time. Then you can move on to the next issue.

**Comment by rpitingolo** [comment]
@eburton9 The primary edits that I made had to do with the macros that convert the ID from the shapefile into the correct format for our needs. What happened is that the last time we did this, the input variable for many of the geographies was called NAME. However, the block group 2020 block shapefile that we used to merge also has a variable called NAME. ArcGIS renamed the variable we usually need to NAME_1. So you will see I added a parameter to the macro, for example `%Octo_Cluster17(invar=Name_1);` This is tricky because when you ran the programs it didn't produce an error in the log. It was creating a variable, but it was using the wrong input and therefor it was not creating it correctly.

You don't have to take any action, I just wanted to explain what I found in the review. Thanks!

**Pull request merged**
