### PR TITLE
Create Octo_ward2022.sas

### PR DESCRIPTION
**Pull request by eburton9**
@rpitingolo

### CODE REVIEW

**Comment by eburton9** [comment]
@rpitingolo the rest of step 3 files

**Comment by rpitingolo** [comment]
@eburton9 thanks I will review.

**Comment by rpitingolo** [comment]
@eburton9 it looks like the datasets block20_ward22, etc. datasets are not correct. I think you may have stat transferred  the wrong dbf file here. The dbf you want to transfer is from the shapefile after you've completed the spatial join. It should have a few thousand rows in it, where each row is a Census block. Please let me know if you need help.

**Comment by rpitingolo** [comment]
@eburton9 2010 program is working now. There was a missing run; from the proc sort that I added. Otherwise looks good. Please go ahead and make these edits to 2000 and 2020.

**Comment by rpitingolo** [comment]
@eburton9 I am getting some invalid 2020 block ID warnings when I run the block20_ward22.sas - can you make sure the shapefile you used is correct? It has a different number of rows than the other 2020 block files.

**Pull request merged**
